name: issusedb
on:
  push:
  issue_comment:
    types:
      - created
      - edited
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo issuse
        run: |
          echo ${{github.event.comment.body}}
      
          
      
